[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=-zstack-size=4096",
]

# [target.x86_64-unknown-linux-gnu]
# rustflags = [
#   "-C", "prefer-dynamic",
# ]
